### ISSUE TITLE
But why? :-P

### ISSUE THREAD

**Issue by tinexw** [davidg-idealo/david-test#3]

**Comment by david-graesser** [comment]
Haha, ja gute Frage.
Wir haben nach möglichen Lösungen gesucht wie wir GitHub und AWS miteinander verdrahten. Dabei stand vor allem im Vordergrund wie man mit ShortLiving Credentials auf AWS Ressourcen von außerhalb zugreifen kann.

Eine Option war GitHub nur als Repo zu nutzen und für CI den AWS-Stack (CodePipeline, CodeBuild) zu nutzen.
Dann hat man zwar das Problem gelöst das man nicht mehr von außerhalb auf AWS Ressourcen zugreifen möchte, aber man verliert natürlich den eigentlich interessanten Teil von GitHub nämlich GitHub-Actions :)

Deswegen hab ich mir kurz CodeStar angeschaut :) Aber zum einen wird das innerhalb der Dev-Community sicherlich nicht so gut ankommen sich jetzt in CodePipeline reinzufummeln und zum anderen hat auch Thoughtworks davon abgeraten die AWS CI Tools für komplexere Projekte zu nutzen: https://www.thoughtworks.com/de/radar/tools?blipid=202104002

Also bleibts bei dem kurzen Ausflug. 🕺

**Comment by tinexw** [comment]
> aber man verliert natürlich den eigentlich interessanten Teil von GitHub nämlich GitHub-Actions :)

Haha, ja!


> Aber zum einen wird das innerhalb der Dev-Community sicherlich nicht so gut ankommen sich jetzt in CodePipeline reinzufummeln und zum anderen hat auch Thoughtworks davon abgeraten die AWS CI Tools für komplexere Projekte zu nutzen: https://www.thoughtworks.com/de/radar/tools?blipid=202104002

100% d'accord! Der einzige Grund, den ich "vertretbar" finde, ist, wenn man ein sehr kleines Team ist, nur eine handvoll von  Komponenten hat, die man nativ daraus deployen kann oder sich quasi nicht leisten kann oder will, noch irgendwas anderes nebenher zu betreiben man also z.B. auch CodeCommit nutzt und wirklich alles im AWS account hat. 

Aber sonst.... das Ding ist halt einfach kein Build Server, das kann quasi nichts außer die bare necessites. Selbst Testergebisse anzeigen ist ein reiner Krampf ([und auch erschreckend neu](https://aws.amazon.com/blogs/devops/test-reports-with-aws-codebuild/)) Von leicht advanced workflows gar nicht mal zu sprechen. GitHub Actions dagegen ist ein Traum 🧚
